homepage_title = "goNews"

db_name = "db"

feed_fetch_period = "12h"
feed_fetch_delay = "60m"

[[feeds]]
url = "https://rss.cbc.ca/lineup/topstories.xml"

[[feeds]]
url = "https://www.schneier.com/blog/atom.xml"

[[feeds]]
url = "https://krebsonsecurity.com/feed/"

# [[feeds]]
# url = "https://googleprojectzero.blogspot.com/feeds/posts/default"



# [[feeds]]
# url = "https://blog.talosintelligence.com/feeds/posts/default"

# [[feeds]]
# url = "https://news.ycombinator.com/rss"

# [[feeds]]
# url = "https://news.softpedia.com/newsRSS/Security-5.xml"

# [[feeds]]
# url = "http://feeds.arstechnica.com/arstechnica/security"

# [[feeds]]
# url = "https://www.wired.com/feed/category/security/latest/rss"

# [[feeds]]
# url = "https://www.vice.com/en_us/rss/section/tech"

# Arxiv example
# [[feeds]]
# url = "http://export.arxiv.org/rss/cs.CR?version=atom_1.0"

# Reddit example
# [[feeds]]
# url = "https://www.reddit.com/r/crypto.rss"
