homepage_title = "goNews"

item_limit = 5

[[feeds]]
url = "https://www.schneier.com/blog/atom.xml"

[[feeds]]
url = "https://krebsonsecurity.com/feed/"

[[feeds]]
url = "https://googleprojectzero.blogspot.com/feeds/posts/default"

[[feeds]]
url = "http://export.arxiv.org/rss/cs.CR?version=atom_1.0"
item_limit = 1

[[feeds]]
url = "http://export.arxiv.org/rss/cs.DS?version=atom_1.0"
item_limit = 1

[[feeds]]
url = "http://export.arxiv.org/rss/cs.DM?version=atom_1.0"
item_limit = 1

[[feeds]]
url = "http://export.arxiv.org/rss/cs.FL?version=atom_1.0"
item_limit = 1

[[feeds]]
url = "http://export.arxiv.org/rss/cs.NI?version=atom_1.0"
item_limit = 1

[[feeds]]
url = "http://export.arxiv.org/rss/cs.OS?version=atom_1.0"
item_limit = 1

[[feeds]]
url = "http://export.arxiv.org/rss/cs.PL?version=atom_1.0"
item_limit = 1

[[feeds]]
url = "http://export.arxiv.org/rss/cs.SE?version=atom_1.0"
item_limit = 1

# [[feeds]]
# url = "http://export.arxiv.org/rss/cs.SC?version=atom_1.0"
# item_limit = 1

# [[feeds]]
# url = "http://export.arxiv.org/rss/cs.IT?version=atom_1.0"
# item_limit = 1

# [[feeds]]
# url = "https://blog.talosintelligence.com/feeds/posts/default"

# [[feeds]]
# url = "https://news.ycombinator.com/rss"
# item_limit = 5

# [[feeds]]
# url = "https://news.softpedia.com/newsRSS/Security-5.xml"

# [[feeds]]
# url = "http://feeds.arstechnica.com/arstechnica/security"

# [[feeds]]
# url = "https://www.wired.com/feed/category/security/latest/rss"

# [[feeds]]
# url = "https://www.vice.com/en_us/rss/section/tech"

# [[feeds]]
# url = "https://www.reddit.com/r/golang.rss"

# [[feeds]]
# url = "https://www.reddit.com/r/netsec.rss"

# [[feeds]]
# url = "https://www.reddit.com/r/devops.rss"

# [[feeds]]
# url = "https://www.reddit.com/r/artc.rss"

# [[feeds]]
# url = "https://www.reddit.com/r/crypto.rss"
