version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/gonews
    entrypoint: ./docker/run.sh
    stdin_open: true
    tty: true
    environment:
      GONEWS_ENV: DEV
