version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./.config:/go/src/gonews/.config:ro
      - gonews_data:/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
volumes:
  gonews_data: {}
