version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - .:/go/src/gonews
      - gonews_data_dev:/data
    stdin_open: true
    tty: true
volumes:
  gonews_data_dev: {}
