version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/go/src/gonews
      - gonews_data_dev:/data
    environment:
      GONEWS_DEBUG: "true"
    entrypoint: "bash"
    stdin_open: true
    tty: true
volumes:
  gonews_data_dev: {}
