version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./.config:/go/src/gonews/.config:ro
      - gonews_data:/data
    entrypoint: "gonews"
volumes:
  gonews_data: {}
