#!/usr/bin/env bash

go install -mod=vendor github.com/golang/mock/mockgen

mkdir -p mock_parser
mockgen gonews/parser Parser > mock_parser/parser.go

mkdir -p mock_db
mockgen gonews/db DB > mock_db/db.go

go test ./...
