#!/usr/bin/env bash

mkdir -p mock_config
mockgen gonews/config Config > mock_config/config.go
mkdir -p mock_fs
mockgen gonews/fs FS,File > mock_fs/fs.go
mkdir -p mock_db
mockgen gonews/db DB > mock_db/db.go
mkdir -p mock_lib
mockgen gonews/lib FeedFetcher,GofeedURLParser,PersistentTimestamp > mock_lib/lib.go
go test ./...
